### ISSUE TITLE
Ensure that vsize is used

### ISSUE THREAD

**Issue by timothyylim** [0xB10C/memo#11]
Hitting the api only returns the size and not the vsize. Both are shown when visiting the actual site:

https://blockstream.info/tx/c1c0e78d69cb302a784661aa3f2d86c81e18be63414f1999be3c464fd7d10169

**Comment by 0xB10C** [comment]
Example SegWit tx: [cffed1ef0398ede623770179bcfef12302a1f0bd8a519911c699fd899353d286](https://blockstream.info/tx/cffed1ef0398ede623770179bcfef12302a1f0bd8a519911c699fd899353d286)

Blockstream.info shows a size of 438 vB and 600 B and a feerate of 200.8 sat/vB (87800sat/438vB)

The [api](https://blockstream.info/api/tx/cffed1ef0398ede623770179bcfef12302a1f0bd8a519911c699fd899353d286) shows `"size":600`.

Thus or feerate calculation is wrong. To get vbyte we should use the `weight/4` which the api provides.
