### ISSUE TITLE
Replace y-axis labels with 'Priority' instead of transaction count?

### ISSUE THREAD

**Issue by timothyylim** [0xB10C/memo#19]
Since the mempool can be considered a queue of transactions and since we sort them by transaction fee, it makes sense to present it to the user as a sort of priority queue.

It doesn't really matter to users exactly how many transactions there are in the mempool but instead, where their transaction is in relation to the others. 

I suggest relabelling the y-axis as:

<img width="448" alt="Skjermbilde 2019-04-26 kl  11 30 53" src="https://user-images.githubusercontent.com/6047346/56798468-12c5cc00-6817-11e9-9a34-11c2b948ca1f.png">

the 'high' label will obviously be at the top of the axis when coded up.

**Comment by 0xB10C** [comment]
I tend to agree that the y-axis needs some work. But I don't like having just ["low", "high"]. Doesn't really give that more information. Additionally there are usually more low-feerate-tx than high-feerate-tx. Showing a user a transaction between low and high on a non-linear graph seems to be only making things harder to understand.

Would having the y-axes as feerate solve a similar problem?
An example would be having e.g. ["1s/byte", "10s/byte", "50s/byte", "100s/byte", "<top>s/byte"] as ticks.
But I guess we'd need to build that function our selfs (which is possible - just needs some fine tuning to stop e.g. "50s/byte" and "100sat/b" from being drawn on top of each other, when there are only few tx between 50s/byte and 100s/byte).

What do you think?

**Comment by 0xB10C** [comment]
I've done some work on this. Bit different that I first though, but I think it gets the job done without removing the y-axis labels. It's currently live on dev.mempool.observer.

What do you think?

![Auswahl_064](https://user-images.githubusercontent.com/19157360/59098169-e6c25e00-891f-11e9-8c95-d0fc57af7d66.png)

**Comment by timothyylim** [comment]
Elegant. It was what I wanted and it keeps clutter to a minimum. Well done :)
