### ISSUE TITLE
Mempool zoom in/out

### ISSUE THREAD

**Issue by MilnMiln** [0xB10C/memo#39]
I'd love to be able to zoom in on a specific region of the mempool, to acheive a finer fee resolution. For example:  (1,3,6,42,170) is somewhat useful, but if I could zoom in on the '6', to see something like (5,8, 5.9, 6.0, 6.1, 6.2), then I can more carefully choose my fee.

**Comment by 0xB10C** [comment]
Thanks for your suggestion. I think I get what you mean: you'd like to see if you can pay just a bit more than e.g. thous 300 transactions paying 6.1 sat/vbyte by paying 6.2 sat/vbyte.

But for one I don't think it really fits into the current mempool chart (as in: don't overload the user with information when first opening the site). Secondly it would increase memory and chart render times quite a bit. Thirdly most wallets don't actually let you pay a that accurate feerate. And finally why not just pay 7 sat/vbyte when there are a lot of transactions with <7 sat/vbyte. What do you think?
